-- liquibase formatted sql

-- changeset eorion:1 dbms:mysql
CREATE TABLE IF NOT EXISTS ENHANCEMENT_DELEGATION
(
    ID
    SERIAL
    PRIMARY
    KEY,
    DELEGATE_NAME
    VARCHAR
(
    255
) NOT NULL,
    OWNER_USER_ID VARCHAR
(
    64
) NOT NULL,
    OWNER_USER_NAME VARCHAR
(
    255
) NOT NULL,
    DELEGATE_TO_USER_ID VARCHAR
(
    64
) NOT NULL,
    DELEGATE_TO_USER_NAME VARCHAR
(
    255
) NOT NULL,
    START_DATE_TS BIGINT NOT NULL,
    END_DATE_TS BIGINT NOT NULL,
    USER_GROUPS VARCHAR
(
    255
),
    TENANT_TXT VARCHAR
(
    64
),
    CREATED_TS BIGINT,
    UPDATED_TS BIGINT,
    CREATE_BY_TXT VARCHAR
(
    20
) DEFAULT NULL,
    UPDATED_BY_TXT VARCHAR
(
    20
) DEFAULT NULL,
    DELETE_FG SMALLINT DEFAULT 0
    );